### ISSUE TITLE
Red play button sizing needs min width adding

### ISSUE THREAD

**Issue by samneter** [samneter/HoopsfixLive#27]
Need to set a min width to the play button and responsive font size - all coming up different sizes atm due to different team name lengths.

**Comment by ChrisGuy** [comment]
Fixture items overflowing the container

**Comment by ChrisGuy** [comment]
@samneter Can you write the fixtures you added so I can replicate

**Comment by samneter** [comment]
BBL - Manchester Giants vs Manchester Giants x 3 and then Plymouth City Patriots vs Manchester Giants.

Assume it is the longer name causing the issue - would prob be the same for Team Solent Kestrels.

**Comment by samneter** [comment]
> @samneter Can you write the fixtures you added so I can replicate

BBL - Manchester Giants vs Manchester Giants x 3 and then Plymouth City Patriots vs Manchester Giants.

Assume it is the longer name causing the issue - would prob be the same for Team Solent Kestrels.

**Comment by ChrisGuy** [comment]
Reconfigured the layout of each stream item to allow more space
