### ISSUE TITLE
User can select same team in both home club and away club fields

### ISSUE THREAD

**Issue by samneter** [samneter/HoopsfixLive#35]
When submitting a new game stream (at http://0.0.0.0:3000/games/new) user can select same team as both home club and away club - need it so whichever team is selected is one field, cannot be selected in the other (because the same team can't play each other).

<img width="577" alt="Screenshot 2022-01-12 at 05 48 23" src="https://user-images.githubusercontent.com/23277161/149071188-ffd3155e-f723-40e3-bfa3-d5c4701afce3.png">

**Comment by ChrisGuy** [comment]
Perhaps onChange of Home team, filter options !match home team selected ?
