### ISSUE TITLE
Better way of displaying teams on club show page

### ISSUE THREAD

**Issue by samneter** [samneter/HoopsfixLive#54]
Need better way to display teams on club show page - should it their names only - though some have a different logo, so maybe need both - team names are long though...any ideas?

I have bodged this together so far lol:

<img width="743" alt="Screenshot 2022-03-02 at 06 12 22" src="https://user-images.githubusercontent.com/23277161/156305874-06495263-a951-42f2-bee3-c04e45fb6792.png">

Comps looks kinda messy too there but might be because we don't have the final logos for each one yet.

**Comment by ChrisGuy** [comment]
Resolved

**Comment by ChrisGuy** [comment]
Resolved
